export enum RentStatus {
  PENDING = 'Pending',
  PARTIAL = 'Partial',
  PAID = 'Paid',
  OVERDUE = 'Overdue',
}

export interface Rent {
  _id: string;
  tenant: {
    _id: string;
    name: string;
    email: string;
    phone?: string;
  };
  flat: {
    _id: string;
    name: string;
  };
  owner?: {
    _id: string;
    name: string;
    phone?: string;
    email?: string;
    address?: string;
  };
  month: string; // Format: "2025-11"
  year: number;
  baseRent: number;
  electricityBill: number;
  gasBill: number;
  waterBill: number;
  serviceBill: number;
  totalAmount: number;
  lateFee: number;
  adjustedTotalAmount: number;
  paidAmount: number;
  dueAmount: number;
  status: RentStatus;
  dueDate: string;
  paidDate?: string;
  paymentMethod?: string;
  note?: string;
  isAutoGenerated?: boolean;
  generatedAt?: string;
  receiptNumber?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateRentDto {
  tenantId: string;
  flatId: string;
  month: string;
  year: number;
  electricityBill?: number;
  gasBill?: number;
  waterBill?: number;
  serviceBill?: number;
  dueDate: string;
  note?: string;
}

export interface UpdateRentDto {
  electricityBill?: number;
  gasBill?: number;
  waterBill?: number;
  serviceBill?: number;
  dueDate?: string;
  paidAmount?: number;
  status?: RentStatus;
  paidDate?: string;
  paymentMethod?: string;
  note?: string;
  lateFee?: number;
  isAutoGenerated?: boolean;
  generatedAt?: string;
  receiptNumber?: string;
}

export interface RecordPaymentDto {
  amount: number;
  paymentMethod: string;
  note?: string;
}

export interface GenerateRentsDto {
  month: string;
  year: number;
  dueDate: string;
}

export interface RentStats {
  totalCollected: number;
  totalPending: number;
  totalOverdue: number;
  totalRent: number;
  paidCount: number;
  pendingCount: number;
  overdueCount: number;
  partialCount: number;
}
